version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - REDIS_PASSWORD=secret123
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', 'secret123']

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    environment:
      # JWT
      - JWT_SECRET=secret
      - JWT_EXPIRATION_TIME=1d

      # DB
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=secret123
      - DB_DATABASE=postgres

      # REDIS
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=secret123

      # APP
      - APP_PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres
